#!/usr/bin/env bash
# =============================================================================
# generate-index.sh — Auto-generate Skill Index for Godmode Plugin
# =============================================================================
# Reads all SKILL.md frontmatter and generates:
#   1. Alphabetical index of all skills
#   2. Category-grouped index (by phase)
#   3. Outputs to docs/auto-generated-index.md
#
# Usage: bash scripts/generate-index.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

SKILLS_DIR="$ROOT_DIR/skills"
OUTPUT_FILE="$ROOT_DIR/docs/auto-generated-index.md"

# Ensure docs directory exists
mkdir -p "$ROOT_DIR/docs"

# ── Collect skill data ──────────────────────────────────────────────────────
# Arrays to store skill info
declare -a skill_names=()
declare -a skill_descriptions=()
declare -a skill_dirs=()
declare -a skill_categories=()

while IFS= read -r skill_file; do
  dir_name="$(basename "$(dirname "$skill_file")")"

  # Check for frontmatter
  first_line="$(head -1 "$skill_file")"
  if [ "$first_line" != "---" ]; then
    continue
  fi

  # Extract name
  name="$(sed -n '2,/^---$/p' "$skill_file" | sed '$d' | grep "^name:" | head -1 | sed 's/^name: *//')"
  if [ -z "$name" ]; then
    name="$dir_name"
  fi

  # Extract description (handle multiline YAML with |)
  desc_line="$(sed -n '2,/^---$/p' "$skill_file" | sed '$d' | grep "^description:" | head -1)"
  if echo "$desc_line" | grep -q '|'; then
    # Multiline description — get the next non-empty indented line
    description="$(sed -n '2,/^---$/p' "$skill_file" | sed '$d' | grep "^description:" -A 20 | tail -n +2 | head -1 | sed 's/^  *//')"
  else
    description="$(echo "$desc_line" | sed 's/^description: *//')"
  fi

  # Truncate description to first sentence for index readability
  description="$(echo "$description" | sed 's/\. .*/\./' | head -c 200)"

  # Determine category based on skill name
  case "$dir_name" in
    think|predict|scenario)
      category="Think (Design & Discovery)" ;;
    plan|build|test|review)
      category="Build (Plan & Implement)" ;;
    optimize|debug|fix|secure)
      category="Optimize (Autonomous Iteration)" ;;
    ship|finish)
      category="Ship (Deliver & Monitor)" ;;
    godmode|setup|verify)
      category="Meta (Always Active)" ;;
    # Infrastructure & DevOps
    deploy|infra|k8s|cicd|pipeline|config|secrets|observe|loadtest|incident|chaos|cost)
      category="Infrastructure & DevOps" ;;
    # Code Quality & Testing
    quality|unittest|e2e|perf|a11y|errortrack|lint|refactor|pattern)
      category="Code Quality & Testing" ;;
    # Architecture & Design
    architect|micro|monorepo|contract|migrate|ddd|schema|event|grpc|graphql)
      category="Architecture & Design" ;;
    # Documentation & Collaboration
    docs|onboard|rfc|adr|pair|learn|dx|prompt|standup|report)
      category="Documentation & Collaboration" ;;
    # Security & Compliance
    auth|rbac|pentest|devsecops|comply|crypto|backup)
      category="Security & Compliance" ;;
    # Frontend & UI
    ui|visual|mobile|pwa|seo|i18n|desktop|webperf)
      category="Frontend & UI" ;;
    # Data & AI
    ml|mlops|query|search|rag|predict|analytics|eval)
      category="Data & AI" ;;
    # Specialized Domains
    api|cli|edge|iot|wasm|web3|pay|email|realtime|queue|storage|state|cache|network|resilience|chart|logging|orm|release|agent|extension|scaffold|git|pr|automate|snapshot|type|integration|errorhandling)
      category="Specialized Domains" ;;
    *)
      category="Other" ;;
  esac

  skill_names+=("$name")
  skill_descriptions+=("$description")
  skill_dirs+=("$dir_name")
  skill_categories+=("$category")
done < <(find "$SKILLS_DIR" -name "SKILL.md" -type f | sort)

total_skills=${#skill_names[@]}

# ── Generate output ─────────────────────────────────────────────────────────

{
  cat <<'HEADER'
<!-- AUTO-GENERATED FILE — Do not edit manually. -->
<!-- Generated by: scripts/generate-index.sh -->
<!-- Re-generate with: bash scripts/generate-index.sh -->

# Godmode Skill Index

HEADER

  echo "**Total skills: $total_skills**"
  echo ""

  # ── Alphabetical Index ──────────────────────────────────────────────────
  echo "---"
  echo ""
  echo "## Alphabetical Index"
  echo ""
  echo "| Skill | Directory | Description |"
  echo "|-------|-----------|-------------|"

  # Create sorted index by skill name
  for i in $(seq 0 $((total_skills - 1))); do
    echo "${skill_names[$i]}|${skill_dirs[$i]}|${skill_descriptions[$i]}"
  done | sort -t'|' -f -k1 | while IFS='|' read -r name dir desc; do
    echo "| **$name** | \`skills/$dir/\` | $desc |"
  done

  echo ""

  # ── Category-Grouped Index ─────────────────────────────────────────────
  echo "---"
  echo ""
  echo "## Skills by Category"
  echo ""

  # Collect unique categories in display order
  declare -a ordered_categories=(
    "Think (Design & Discovery)"
    "Build (Plan & Implement)"
    "Optimize (Autonomous Iteration)"
    "Ship (Deliver & Monitor)"
    "Meta (Always Active)"
    "Infrastructure & DevOps"
    "Code Quality & Testing"
    "Architecture & Design"
    "Documentation & Collaboration"
    "Security & Compliance"
    "Frontend & UI"
    "Data & AI"
    "Specialized Domains"
    "Other"
  )

  for cat in "${ordered_categories[@]}"; do
    # Check if any skills belong to this category
    cat_count=0
    for i in $(seq 0 $((total_skills - 1))); do
      if [ "${skill_categories[$i]}" = "$cat" ]; then
        cat_count=$((cat_count + 1))
      fi
    done

    if [ "$cat_count" -eq 0 ]; then
      continue
    fi

    echo "### $cat ($cat_count skills)"
    echo ""
    echo "| Skill | Directory | Description |"
    echo "|-------|-----------|-------------|"

    for i in $(seq 0 $((total_skills - 1))); do
      if [ "${skill_categories[$i]}" = "$cat" ]; then
        echo "| **${skill_names[$i]}** | \`skills/${skill_dirs[$i]}/\` | ${skill_descriptions[$i]} |"
      fi
    done

    echo ""
  done

  # ── Footer ─────────────────────────────────────────────────────────────
  echo "---"
  echo ""
  echo "*Generated on $(date -u '+%Y-%m-%d %H:%M:%S UTC') by \`scripts/generate-index.sh\`*"

} > "$OUTPUT_FILE"

echo "Generated skill index at: $OUTPUT_FILE"
echo "Total skills indexed: $total_skills"
